spring.application.name=projectmanagementsystemApplication

server.port=5454

spring.datasource.platform=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/yt_projectmanagementsystem
spring.datasource.username=root
spring.datasource.password=newpassword
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.docker.compose.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akshayhiremath744@gmail.com
spring.mail.password=licd ygvc curk timg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


